Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'peribot-groupme.gemspec'

Style/Documentation:
  Exclude:
    - 'lib/peribot/groupme/version.rb'

Style/SignalException:
  EnforcedStyle: only_raise

AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - 'bin/**/*'
