language: ruby
rvm:
  - 2.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - jruby-9.0.4.0
  - rbx
matrix:
  allow_failures:
    - rvm: rbx

before_install: gem install bundler -v "~> 1.11"
script: bundle exec rake spec
